name: redis_client
version: 0.1.17
authors:
- Demis Bellot <demis.bellot@gmail.com>
- Adam Singer <financeCoding@gmail.com>
- Matias Meno <m@tias.me>
- Baruch Berger <baruchberger@gmail.com>
- Max Horstmann <max.horstmann@gmail.com>
- Matthew Butler <butler.matthew@gmail.com>
description: A high-performance async/non-blocking Redis client for Dart.
homepage: https://github.com/dartist/redis_client
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  logging: '>=0.9.0 <0.12.0'
dev_dependencies:
  test: '>=0.12.0 <0.13.0'
  mockito: '>=0.11.0 <0.12.0'
  benchmark_harness: 'any'
