name: redis_client
version: 0.1.11
authors:
- Demis Bellot <demis.bellot@gmail.com>
- Adam Singer <financeCoding@gmail.com>
- Matias Meno <m@tias.me>
- Baruch Berger <baruchberger@gmail.com>
- Max Horstmann <max.horstmann@gmail.com>
description: A high-performance async/non-blocking Redis client for Dart.
homepage: https://github.com/dartist/redis_client
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  logging: '>=0.9.0 <0.9.1'
  unittest: '>=0.9.0 < 0.10.0'
